[project]
name = "openai-websearch-mcp"
version = "0.6.0"
description = "OpenAI web search and brainstorming with reasoning models as MCP server"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pydantic_extra_types==2.11.1",
    "pydantic>=2.11.0,<3.0.0",
    "mcp==2.2.0",
    "tzdata==2026.3",
    "openai==3.10.0",
    "typer==0.27.2"
]


[project.scripts]
openai-websearch-mcp = "openai_websearch_mcp:main"
openai-websearch-mcp-install = "openai_websearch_mcp.cli:app"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[dependency-groups]
dev = [
    "pytest>=8.0",
]
